### ISSUE TITLE
Blockquote alert errors with MDX and Next.js

### ISSUE THREAD

**Issue by TommySorensen** [jaywcjlove/remark-github-blockquote-alert#5]
Just wanted to let you know this plugin does not work with latest version of Next.js using MDX from https://nextjs.org/docs/app/building-your-application/configuring/mdx using turbopack https://nextjs.org/docs/app/building-your-application/configuring/mdx#using-plugins-with-turbopack

I havent added an example, but i'm using pretty simple setup like the docs
```js
// next.config.mjs

import createMDX from '@next/mdx';

const nextConfig = {
  pageExtensions: ['mdx', 'tsx'],
};

const withMDX = createMDX({
  options: {
    remarkPlugins: [[''remark-github-blockquote-alert''],['remark-gfm']],
    rehypePlugins: [],
  },
});

export default withMDX(nextConfig);
```

It throws this error:
```
 ⨯ ./src/app/test/page.mdx
Error evaluating Node.js code
TypeError: attacher.call is not a function
    [at Function.freeze (node_modules/.pnpm/unified@11.0.5/node_modules/unified/lib/index.js:636:36)]
    [at Function.process (node_modules/.pnpm/unified@11.0.5/node_modules/unified/lib/index.js:716:10)]
    [at process (node_modules/.pnpm/@mdx-js+mdx@3.1.0_acorn@8.14.0/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:63:22)]
    [at Proxy.loader (node_modules/.pnpm/@mdx-js+loader@3.1.0_acorn@8.14.0/node_modules/@mdx-js/loader/lib/index.js:89:3)]
    [at /node_modules/.pnpm/@mdx-js+loader@3.1.0_acorn@8.14.0/node_modules/@mdx-js/loader/index.cjs:32:26]
```

So my question is if this package been tested with MDX?

**Comment by jaywcjlove** [comment]
@TommySorensen  The potential issue lies in the format of remark-github-blockquote-alert:
There is an extra set of quotes around the plugin name. The correct format should be:

```js
remarkPlugins: [['remark-github-blockquote-alert'], ['remark-gfm']],
```

However, I’m not entirely sure if your error is caused by remark-github-blockquote-alert.

**Comment by TommySorensen** [comment]
My bad. This was a copy paste mistake when adding copying the code to the Github Issue. I can confirm that the issue is still there with correctly configuration.
```
remarkPlugins: [['remark-github-blockquote-alert'], ['remark-gfm']],
```

It looks like the error rely inside MDX code, but cause by this plugin. Everything works fine if i remove the plugin from the next.config. I tested both with and without using the syntax for alerts

**Comment by jaywcjlove** [comment]
I'm a bit puzzled by this issue because I haven't encountered anything similar when using it elsewhere. @TommySorensen

**Comment by renbou** [comment]
@jaywcjlove The issue is due to the lack of a default-export for "remarkAlert". Adding a simple wrapper package for "remark-github-blockquote-alert" fixes it

<img width="596" alt="Image" src="https://github.com/user-attachments/assets/65665a0c-639d-424c-b35c-67307172863c" />

**Comment by renbou** [comment]
See #7 for a fix

**Comment by jaywcjlove** [comment]
@renbou thx!
